import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: 'demo'}],
  // react: [{type: 'autogenerated', dirName: 'react'}],
  react:{
    基本概念:[{type: 'autogenerated', dirName: 'react/base'}]
  },
  algorithm: [{type: 'autogenerated', dirName: 'algorithm'},]
  // 框架: {
  //   React: [{ type: 'autogenerated', dirName: 'frameworks/react' }],
  //   Vue: [{ type: 'autogenerated', dirName: 'frameworks/vue' }],
  //   微信: ['frameworks/wx/h5'],
  // },
  // react: {
  //   '基本概念': ['react/macro-structure'],
  // },
 

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
